id = "grabe2015"
title = "Grabe 2015 (LM template)"
native_space = "GRABE"
asset = "grabe2015_glomeruli"
citation = "Grabe V, et al. (2015) Curr Biol 25(16):2215-2216"
doi = "10.1016/j.cub.2015.07.036"
